In [25]:
import pandas as pd

# Provide the raw GitHub URL of the CSV file
url = "https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day26-ordinal-encoding/customer.csv"
df = pd.read_csv(url)
df=df.iloc[:,2:]
df.sample(5)

     review education purchased
11     Good        UG       Yes
10     Good        UG       Yes
4   Average        UG        No
34  Average    School        No
42     Good        PG       Yes

     review education
9      Good        UG
25     Good    School
10     Good        UG
32  Average        UG
27     Poor        PG
44  Average        UG
28     Poor    School
31     Poor    School
30  Average        UG
26     Poor        PG
24  Average        PG
4   Average        UG
33     Good        PG
11     Good        UG
37  Average        PG
19     Poor        PG
38     Good    School
14     Poor        PG
12     Poor    School
49     Good        UG
15     Poor        UG
39     Poor        PG
7      Poor    School
23     Good    School
3      Good        PG
29  Average        UG
1      Poor        UG
22     Poor        PG
13  Average    School
5   Average    School
48     Good        UG
36     Good        UG
17     Poor        UG
40     Good    School
8   Average        UG
41     Good        PG
2      Good        PG
34  Average    School
45     Poor        PG
18     Good    School

In [73]:
# train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)
X_train



from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
oe.fit(X_train)
X_train=oe.transform(X_train)
X_test=oe.transform(X_test)
#similarly for label encoder
# it is used explicitly for the output column only 
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder() # the values will be given randomly e.g. no->1 and yes->2
le.fit(y_train)
y_train=le.transform(y_train)
y_test=le.transform(y_test)
le.classes_ # to identify the values of the attributes

array(['No', 'Yes'], dtype=object)